services:
  rest-api-service:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    image: hazardsoft/library-rest-api:latest
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    depends_on:
      - database-service
    ports:
      - ${PORT}:${PORT}
    networks:
      - library
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database-service:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    restart: on-failure:5
    volumes:
      - ./src:/app/src
      - ./test:/app/test
  database-service:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: hazardsoft/library-database:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    networks:
      - library
    restart: on-failure:5
    volumes:
      - pg-data:${PGDATA}

volumes:
  pg-data:
    name: pg-data

networks:
  library:
    name: library-service-network
