services:
  rest-api-service:
    image: rest-api:latest
    command: sh -c "npx prisma db seed && npm run start:dev"
    depends_on:
      - database-service
    ports:
      - ${PORT}:${PORT}
    networks:
      - library
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database-service:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    restart: on-failure:5
    volumes:
      - ./src:/app/src
  database-service:
    image: hazardsoft/rest-database:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    networks:
      - library
    volumes:
      - pg-data:${PGDATA}
      - ${PWD}/prisma/migrations/${PRISMA_MIGRATION}:/docker-entrypoint-initdb.d
      - ${PWD}/postgresql/postgresql.conf:${PGDATA}/postgresql.conf

volumes:
  pg-data:

networks:
  library:
    name: library-service-network
