name: rest-app-prod
services:
  rest-api-service:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
    image: hazardsoft/library-rest-api:latest
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start:prod"
    depends_on:
      database-service:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    networks:
      - library
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database-service:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    restart: always
  database-service:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    image: hazardsoft/library-database:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    networks:
      - library
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always

networks:
  library:
    name: library-service-network
    driver: bridge
